# Generated by Django 5.1.4 on 2025-01-31 08:56

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_order_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.image_file_path
            ),
        ),
    ]
